language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
  # ' - CODECOV_TOKEN="e9f72994-5c87-4e05-940b-670c4ad71fd7"'
   #' - CODECOV_TOKEN="9ec9b366-f77c-46a6-8145-3bea329f6d79"'
    - CODECOV_TOKEN="7f3053d4-1c02-4fca-a726-bd911042089c"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - novopashinva@gmail.com
    on_success: never # default: change
    on_failure: always # default: always